language: node_js
node_js: 8
os: linux
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
  - npm install
  - npm run vscode:prepublish
cache:
  directories:
    - node_modules
jobs:
  include:
  - stage: Check
    script:
    - ./tools/check_signed_off.sh
  - stage: Build
    script:
    - npm run compile
  - stage: Test
    script:
    - npm run test
