language: node_js
node_js: 8
os: linux
install:
  - npm install
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
jobs:
  include:
  - stage: Check
    script:
    - npm run travis:check-signed-off
  - stage: Build
    script:
    - npm run compile
